### ISSUE TITLE
Will the connectivity be checked whenever a network change is detected?

### ISSUE THREAD

**Issue by mcg95** [JobGetabu/DroidNet#3]
@Override
    public void onInternetConnectivityChanged(boolean isConnected) {
      
        if (isConnected) {
            //do Stuff with internet
            netIsOn();
        } else {
            //no internet
            netIsOff();
        }
    }

Will this function be run if I am in the middle of a process and the internet connection is lost? I want to display a dialog saying there is an issue with the internet.

**Comment by JobGetabu** [comment]
It triggers every time theirs a network change
